# Generated by Django 5.2.4 on 2025-08-25 13:38

import django.db.models.deletion
import evidencias.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadeiaCustomia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_movimentacao', models.CharField(choices=[('coleta', 'Coleta'), ('transferencia', 'Transferência'), ('analise', 'Análise'), ('devolucao', 'Devolução'), ('armazenamento', 'Armazenamento'), ('destruicao', 'Destruição')], max_length=20)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('local_origem', models.CharField(blank=True, max_length=200)),
                ('local_destino', models.CharField(max_length=200)),
                ('motivo', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('assinatura_digital', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_evidencia', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('data_coleta', models.DateTimeField()),
                ('local_coleta', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('coletada', 'Coletada'), ('em_analise', 'Em Análise'), ('analisada', 'Analisada'), ('devolvida', 'Devolvida'), ('destruida', 'Destruída')], default='coletada', max_length=20)),
                ('local_armazenamento', models.CharField(max_length=200)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensoes', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('estado_conservacao', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lacrada', models.BooleanField(default=False)),
                ('numero_lacre', models.CharField(blank=True, max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_coleta'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requer_pericia', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(choices=[('documento', 'Documento'), ('foto', 'Fotografia'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('relatorio', 'Relatório'), ('laudo', 'Laudo'), ('outro', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to=evidencias.models.upload_arquivo_path)),
                ('tamanho_arquivo', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('resolucao', models.CharField(blank=True, max_length=20)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('confidencial', models.BooleanField(default=False)),
                ('hash_arquivo', models.CharField(blank=True, max_length=64)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='casos.caso')),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
    ]
