# Generated by Django 5.2.4 on 2025-08-25 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0002_initial'),
        ('evidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='uploadado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadeiacustomia',
            name='responsavel_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_saida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadeiacustomia',
            name='responsavel_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='coletado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_coletadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='custodia_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_custodia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadeiacustomia',
            name='evidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeia_custodia', to='evidencias.evidencia'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='evidencias.evidencia'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidencias.tipoevidencia'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['numero_evidencia'], name='evidencias__numero__202db0_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['caso'], name='evidencias__caso_id_5483bc_idx'),
        ),
    ]
