# Generated by Django 5.2.4 on 2025-09-14 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DNA', 'DNA'), ('BALISTICA', 'Balística'), ('TOXICOLOGIA', 'Toxicologia'), ('DIGITAIS', 'Digitais')], max_length=13)),
                ('resultado', models.TextField()),
                ('conclusao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pericias', to='evidencias.evidencia')),
            ],
        ),
    ]
