# Generated by Django 5.2.4 on 2025-09-14 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0003_pericia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pericia',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pericia_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
