# Generated by Django 5.2.7 on 2025-11-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0004_pericia_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='evidencia',
        ),
    ]
