# Generated by Django 5.2.7 on 2025-11-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0005_remove_arquivo_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='caso',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='evidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='evidencias.evidencia'),
        ),
    ]
