# Generated by Django 5.2.7 on 2025-11-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0006_remove_arquivo_caso_arquivo_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='evidence/'),
        ),
    ]
