# Generated by Django 5.2.4 on 2025-08-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='marcas_distintivas',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='rg',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bi',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
