# Generated by Django 5.2.4 on 2025-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_pessoa_marcas_distintivas_remove_pessoa_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nacionalidade',
            field=models.CharField(default='Angolana', max_length=50),
        ),
    ]
