# Generated by Django 5.2.4 on 2025-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_endereco_bairro_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('temporario', 'Temporário'), ('antigo', 'Antigo')], max_length=20),
        ),
    ]
