# Generated by Django 5.2.4 on 2025-09-14 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_endereco_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('grau_confianca', models.CharField(max_length=50)),
                ('pessoa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_destino', to='usuario.pessoa')),
                ('pessoa_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_origem', to='usuario.pessoa')),
            ],
        ),
    ]
