# Generated by Django 5.2.4 on 2025-09-14 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_conexao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexao',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conexao_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conexao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
