# Generated by Django 5.2.7 on 2025-10-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_conexao_criado_por_conexao_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaReconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='faces/')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='HistoricoReconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_verificacao', models.ImageField(upload_to='verificacoes/')),
                ('confianca', models.FloatField(blank=True, null=True)),
                ('reconhecido', models.BooleanField(default=False)),
                ('data_verificacao', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.pessoareconhecimento')),
            ],
            options={
                'verbose_name_plural': 'Histórico de Reconhecimentos',
                'ordering': ['-data_verificacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroReconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_capturada', models.ImageField(upload_to='reconhecimentos/')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('confianca', models.FloatField(blank=True, null=True)),
                ('reconhecida', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.pessoa')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
