# Generated by Django 5.2.7 on 2025-10-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_pessoareconhecimento_historicoreconhecimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoareconhecimento',
            options={'verbose_name_plural': 'Reconhecimentos'},
        ),
        migrations.AddField(
            model_name='pessoareconhecimento',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='envolvimento', to='usuario.pessoa'),
            preserve_default=False,
        ),
    ]
