# Generated by Django 5.2.7 on 2025-10-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_pessoareconhecimento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoareconhecimento',
            name='nome',
        ),
    ]
