# Generated by Django 5.2.7 on 2025-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_pessoareconhecimento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoareconhecimento',
            name='nome',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
