# Generated by Django 5.2.7 on 2025-10-20 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_pessoareconhecimento_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='profile')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pessoareconhecimento',
            options={'ordering': ['-data_cadastro'], 'verbose_name_plural': 'Reconhecimentos'},
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bi',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Não informado')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_principal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_secundario',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='pessoareconhecimento',
            index=models.Index(fields=['nome'], name='usuario_pes_nome_f323f0_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoareconhecimento',
            index=models.Index(fields=['foto'], name='usuario_pes_foto_f864c2_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoareconhecimento',
            index=models.Index(fields=['embedding'], name='usuario_pes_embeddi_48a65c_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
