# Generated by Django 5.2.7 on 2025-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_profile_alter_pessoareconhecimento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
