# Generated by Django 5.2.7 on 2025-10-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_alter_profile_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone_principal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone_secundario',
        ),
    ]
