# Generated by Django 5.2.7 on 2025-11-04 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_remove_usuario_telefone_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoreconhecimento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pessoareconhecimento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
