# Generated by Django 5.2.4 on 2025-08-25 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_caso', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('suspenso', 'Suspenso'), ('concluido', 'Concluído'), ('arquivado', 'Arquivado')], default='aberto', max_length=20)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente'), (5, 'Crítica')], default=2)),
                ('data_ocorrencia', models.DateTimeField()),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('prazo_conclusao', models.DateTimeField(blank=True, null=True)),
                ('local_ocorrencia', models.CharField(max_length=300)),
                ('delegacia_origem', models.CharField(max_length=100)),
                ('comarca', models.CharField(max_length=100)),
                ('numero_inquerito', models.CharField(blank=True, max_length=50)),
                ('numero_processo', models.CharField(blank=True, max_length=50)),
                ('vara_judicial', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('observacoes_internas', models.TextField(blank=True)),
                ('confidencial', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('interno', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_comentario'],
            },
        ),
        migrations.CreateModel(
            name='EnvolvimentoCaso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_envolvimento', models.CharField(choices=[('suspeito', 'Suspeito'), ('vitima', 'Vítima'), ('testemunha', 'Testemunha'), ('informante', 'Informante'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data_envolvimento', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('crime', 'Ocorrência do Crime'), ('denuncia', 'Denúncia/Descoberta'), ('prisao', 'Prisão'), ('depoimento', 'Depoimento'), ('pericia', 'Perícia'), ('busca_apreensao', 'Busca e Apreensão'), ('audiencia', 'Audiência'), ('sentenca', 'Sentença'), ('recurso', 'Recurso'), ('outro', 'Outro')], max_length=20)),
                ('importancia', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Crítica')], default=2)),
                ('localizacao', models.CharField(blank=True, max_length=300)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('caso_atribuido', 'Caso Atribuído'), ('prazo_vencendo', 'Prazo Vencendo'), ('evidencia_coletada', 'Evidência Coletada'), ('evento_timeline', 'Evento Timeline'), ('mensagem', 'Mensagem'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(choices=[('investigacao', 'Relatório de Investigação'), ('final', 'Relatório Final'), ('pericia', 'Relatório de Perícia'), ('estatistico', 'Relatório Estatístico'), ('timeline', 'Relatório Timeline'), ('personalizado', 'Relatório Personalizado')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('assinado', models.BooleanField(default=False)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='relatorios/')),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='TipoCrime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField()),
                ('gravidade', models.IntegerField(choices=[(1, 'Leve'), (2, 'Média'), (3, 'Grave'), (4, 'Gravíssima')])),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
