# Generated by Django 5.2.4 on 2025-08-25 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        ('evidencias', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='delegado_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_delegado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='investigador_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_principais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='investigadores_apoio',
            field=models.ManyToManyField(blank=True, related_name='casos_apoio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='envolvimentocaso',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envolvimentos', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='envolvimentocaso',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envolvimentos', to='usuario.pessoa'),
        ),
        migrations.AddField(
            model_name='eventotimeline',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_timeline', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='eventotimeline',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventotimeline',
            name='evidencias_relacionadas',
            field=models.ManyToManyField(blank=True, to='evidencias.evidencia'),
        ),
        migrations.AddField(
            model_name='eventotimeline',
            name='investigador_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventotimeline',
            name='pessoas_envolvidas',
            field=models.ManyToManyField(blank=True, to='usuario.pessoa'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casos.caso'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='assinado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_assinados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='gerado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caso',
            name='tipo_crime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.tipocrime'),
        ),
        migrations.AlterUniqueTogether(
            name='envolvimentocaso',
            unique_together={('caso', 'pessoa', 'tipo_envolvimento')},
        ),
        migrations.AddIndex(
            model_name='eventotimeline',
            index=models.Index(fields=['caso', 'data_hora'], name='casos_event_caso_id_00d9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventotimeline',
            index=models.Index(fields=['tipo_evento'], name='casos_event_tipo_ev_a86eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['numero_caso'], name='casos_caso_numero__75eba2_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['status'], name='casos_caso_status_5851ec_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['data_ocorrencia'], name='casos_caso_data_oc_783c43_idx'),
        ),
    ]
