# Generated by Django 5.2.4 on 2025-08-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocrime',
            name='codigo',
        ),
    ]
