# Generated by Django 5.2.4 on 2025-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_remove_tipocrime_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotimeline',
            name='coordenadas_lat',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventotimeline',
            name='coordenadas_lng',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
