# Generated by Django 5.2.4 on 2025-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_alter_eventotimeline_coordenadas_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotimeline',
            name='coordenadas_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventotimeline',
            name='coordenadas_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
