# Generated by Django 5.2.4 on 2025-09-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0005_alter_eventotimeline_coordenadas_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotimeline',
            name='coordenadas_lat',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventotimeline',
            name='coordenadas_lng',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
