# Generated by Django 5.2.4 on 2025-09-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0007_alter_eventotimeline_coordenadas_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotimeline',
            name='coordenadas_lat',
            field=models.CharField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventotimeline',
            name='coordenadas_lng',
            field=models.CharField(blank=True, null=True),
        ),
    ]
